services:
  postgres:
    image: postgres:16.1
    container_name: postgres
    ports:
      - "5433:5432"
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_USER: "postgres_user"
      POSTGRES_PASSWORD: "postgres_password"
      POSTGRES_DB: "postgres_db"
    command: ["postgres", "-c", "wal_level=logical"]
    networks:
      odax_network:
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres_user -d postgres_db"]
      interval: 5s
      timeout: 5s
      retries: 24

  postgres-bootstrap:
    image: python:3.11-slim
    container_name: postgres-bootstrap
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_USER: "postgres_user"
      POSTGRES_PASSWORD: "postgres_password"
      POSTGRES_DB: "postgres_db"
      POSTGRES_HOST: "postgres"
      POSTGRES_PORT: "5432"
    volumes:
      - ./data:/app/data
      - ./conf:/app/conf
      - ./script:/app/script
    working_dir: /app

    networks:
      odax_network:
    command:
      sh -c "
      apt-get update && apt-get install -y postgresql-client &&
      pip install --no-cache-dir -r /app/conf/requirements.txt &&
      psql -h postgres -U postgres_user -d postgres_db -f /app/script/ddl-nebel.sql &&
      python /app/script/seed_airpollution_scheme.py &&
      python /app/script/seed_healthinsurance_scheme.py
      "
    depends_on:
      postgres:
        condition: service_healthy