services:
  postgres:
    image: postgres:16.1
    container_name: postgres
    ports:
      - "5433:5432"
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_USER: "postgres_user"
      POSTGRES_PASSWORD: "postgres_password"
      POSTGRES_DB: "postgres_db"
    command: ["postgres", "-c", "wal_level=logical"]
    volumes:
      - ./data/initialize_airpollution_scheme.sql:/docker-entrypoint-initdb.d/initialize_airpollution_scheme.sql
      - ./data/initialize_healthinsurance_scheme.sql:/docker-entrypoint-initdb.d/initialize_healthinsurance_scheme.sql
      - ./superset/sql/superset_init.sql:/docker-entrypoint-initdb.d/03_superset_init.sql

    networks:
      odax_network:
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres_user -d postgres_db"]
      interval: 5s
      timeout: 5s
      retries: 24

