networks:
  odax_network:
    driver: bridge
    name: odax_network

include:
  - postgres/docker_compose.yml
  - pgadmin/docker_compose.yml
  - mage/docker-compose.yml
  - superset/docker_compose.yml


