name: CI - Python Lint & Tests

on:
  push:
    branches: ["**"]          # run on any branch
  pull_request:
    branches: ["main"]        # run for PRs into main

jobs:
  lint-and-test:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout code
      - uses: actions/checkout@v4

      # 2. Set up Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"  # or match your project

      # 3. Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install

      # 4. Lint check (PEP8 via flake8)
      - name: Run PEP8 check
        run: |
          flake8 .

      # 5. Run tests if folder exists
      - name: Run unit tests
        run: |
          if [ -d tests ]; then
            pytest tests --maxfail=5 --disable-warnings -q
          else
            echo "No tests/ folder found, skipping unit tests."
          fi
