name: CI - Python Lint & Tests

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["main"]

jobs:
  lint-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Poetry & dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install --no-interaction --no-ansi --no-root
          # If you move pytest/flake8 to [tool.poetry.group.dev.dependencies]
          # use: poetry install --no-interaction --no-ansi --no-root --with dev

      - name: Run PEP8 check
        run: poetry run flake8 .

      - name: Run unit tests
        run: |
          if [ -d tests ]; then
            poetry run pytest tests --maxfail=5 --disable-warnings -q
          else
            echo "No tests/ folder found, skipping unit tests."
          fi
